/**
 * drizzle-kit generate で生成された SQL を
 * DO ランタイム用の TypeScript バンドルに変換するスクリプト
 *
 * Usage: npx tsx scripts/bundle-migrations.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const migrationsDir = join(import.meta.dirname, "../src/migrations");
const journal = JSON.parse(
  readFileSync(join(migrationsDir, "meta/_journal.json"), "utf-8"),
);

const entries: { tag: string; varName: string; sql: string }[] = [];

for (const entry of journal.entries) {
  const sql = readFileSync(join(migrationsDir, `${entry.tag}.sql`), "utf-8");
  const varName = `m${String(entry.idx).padStart(4, "0")}`;
  entries.push({ tag: entry.tag, varName, sql });
}

const output = `// Auto-generated by scripts/bundle-migrations.ts — do not edit manually

const journal = ${JSON.stringify(journal, null, 2)} as const;

${entries.map((e) => `const ${e.varName} = ${JSON.stringify(e.sql)};`).join("\n\n")}

export default {
  journal,
  migrations: {
${entries.map((e) => `    ${e.varName}: ${e.varName},`).join("\n")}
  },
};
`;

const outPath = join(migrationsDir, "index.ts");
writeFileSync(outPath, output);
console.log(`✅ Bundled ${entries.length} migration(s) → src/migrations/index.ts`);
